version: "3"

services:
  user:
    build:
      context: ./User
      dockerfile: Dockerfile
    ports:
      - "3002:3002"

  cart:
    build:
      context: ./Cart
      dockerfile: Dockerfile
    ports:
      - "3003:3003"

  shop:
    build:
      context: ./Shop
      dockerfile: Dockerfile
    ports:
      - "3004:3004"

  category:
    build:
      context: ./Category
      dockerfile: Dockerfile
    ports:
      - "3005:3005"

  product:
    build:
      context: ./Product
      dockerfile: Dockerfile
    ports:
      - "3006:3006"

  review:
    build:
      context: ./Review
      dockerfile: Dockerfile
    ports:
      - "3007:3007"

  promotion:
    build:
      context: ./Promotion
      dockerfile: Dockerfile
    ports:
      - "3008:3008"

  order:
    build:
      context: ./Order
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
