version: "3"

services:
  user:
    build:
      context: ./User
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/app/user

  cart:
    build:
      context: ./Cart
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - .:/usr/src/app/cart

  shop:
    build:
      context: ./Shop
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    volumes:
      - .:/usr/src/app/shop

  category:
    build:
      context: ./Category
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    volumes:
      - .:/usr/src/app/category

  product:
    build:
      context: ./Product
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    volumes:
      - .:/usr/src/app/product

  review:
    build:
      context: ./Review
      dockerfile: Dockerfile
    ports:
      - "3007:3007"
    volumes:
      - .:/usr/src/app/review

  promotion:
    build:
      context: ./Promotion
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    volumes:
      - .:/usr/src/app/promotion

  order:
    build:
      context: ./Order
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    volumes:
      - .:/usr/src/app/order
